### ISSUE TITLE
Atividade #1 - Habilitar DISCUSSIONS neste repositório

### ISSUE THREAD

**Issue by HamiltonFilho** [Felipe-T-B/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-18#4]
Caro grupo,

Por favor habilitar a funcionalidade DISCUSSIONS neste repositório

O administrador do repositório deve clicar na aba Settings, e dentro da Aba General clicar no checkbox DISCUSSIONS

Esta atividade deve ser concluída o quanto antes!

![github-discussions](https://github.com/Felipe-T-B/ceunsp_arduino/assets/28486980/49f03d8b-97a4-4205-aa2e-9c294b57ac38)

**Comment by HamiltonFilho** [comment]
Por favor tomar ação neste item!

**Comment by Felipe-T-B** [comment]
Concluido
