### ISSUE TITLE
História 1 - Como usuário no controle de direção, quero que o carro de Arduino ande para todas direções

### ISSUE THREAD

**Issue by Felipe-T-B** [Felipe-T-B/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-18#5]
Eu como usuário no controle de direção, quero que o carro de Arduino ande para todas direções.

**Comment by HamiltonFilho** [comment]
Esta é uma mensagem para confirmar que este exercício foi considerado ENTREGUE COM SUCESSO pelo grupo, e isto irá refletir de forma positiva na nota A2 de todos os membros desta equipe
